/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Controlador.ControladorBoleta;

/**
 *
 * @author Programmer
 */
public class ConsultarBoleta extends javax.swing.JPanel {

    /**
     * Creates new form ConsultarBoleta
     */
    public ConsultarBoleta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jtxtDniCliente = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jbtnBuscarBoletas = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblTablaBoletas = new javax.swing.JTable();
        jLabel27 = new javax.swing.JLabel();

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Malgun Gothic", 0, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(105, 105, 118));
        jLabel10.setText("DNI Cliente: ");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 120, 40));

        jtxtDniCliente.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        jtxtDniCliente.setBorder(null);
        jtxtDniCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtDniClienteActionPerformed(evt);
            }
        });
        jPanel2.add(jtxtDniCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 55, 210, -1));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 210, 10));

        jbtnBuscarBoletas.setBackground(new java.awt.Color(255, 255, 254));
        jbtnBuscarBoletas.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        jbtnBuscarBoletas.setForeground(new java.awt.Color(105, 105, 118));
        jbtnBuscarBoletas.setText("BUSCAR");
        jPanel2.add(jbtnBuscarBoletas, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 50, 100, 30));

        jtblTablaBoletas.setFont(new java.awt.Font("Malgun Gothic", 0, 14)); // NOI18N
        jtblTablaBoletas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtblTablaBoletas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtblTablaBoletasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtblTablaBoletas);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 630, 570));

        jLabel27.setBackground(new java.awt.Color(105, 105, 118));
        jLabel27.setFont(new java.awt.Font("Malgun Gothic", 0, 24)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(105, 105, 118));
        jLabel27.setText("Lista de boletas");
        jPanel2.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 710, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 840, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 790, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtDniClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtDniClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtDniClienteActionPerformed

    private void jtblTablaBoletasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtblTablaBoletasMouseClicked
        int fila = jtblTablaBoletas.getSelectedRow();
        if (fila != -1) {
            String idBoleta = String.valueOf(jtblTablaBoletas.getValueAt(fila, 0));
            new ControladorBoleta(new VentanaBoleta(), Integer.parseInt(idBoleta));
        }
    }//GEN-LAST:event_jtblTablaBoletasMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator3;
    public javax.swing.JButton jbtnBuscarBoletas;
    public javax.swing.JTable jtblTablaBoletas;
    public javax.swing.JTextField jtxtDniCliente;
    // End of variables declaration//GEN-END:variables
}
