/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Controlador.ControladorConsultaBoleta;
import Controlador.ControladorPanelPrincipal;
import DAO.CRUDBoleta;
import javax.swing.WindowConstants;

/**
 *
 * @author Programmer
 */
public class ConsultarReporte extends javax.swing.JPanel {

    /**
     * Creates new form ConsultarRepeorte
     */
    public ConsultarReporte() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jdchFechaInicial = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jdchFechaFinal = new com.toedter.calendar.JDateChooser();
        jbtnBuscarReportes = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblTablaReportes = new javax.swing.JTable();
        jLabel27 = new javax.swing.JLabel();

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Malgun Gothic", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(105, 105, 118));
        jLabel3.setText("Desde:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, -1, 30));

        jdchFechaInicial.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel2.add(jdchFechaInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 130, 30));

        jLabel1.setFont(new java.awt.Font("Malgun Gothic", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(105, 105, 118));
        jLabel1.setText("Hasta:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, -1, 30));

        jdchFechaFinal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel2.add(jdchFechaFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, 130, 30));

        jbtnBuscarReportes.setBackground(new java.awt.Color(255, 255, 254));
        jbtnBuscarReportes.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        jbtnBuscarReportes.setForeground(new java.awt.Color(105, 105, 118));
        jbtnBuscarReportes.setText("BUSCAR");
        jPanel2.add(jbtnBuscarReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 50, 100, 30));

        jtblTablaReportes.setFont(new java.awt.Font("Malgun Gothic", 0, 14)); // NOI18N
        jtblTablaReportes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtblTablaReportes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtblTablaReportesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jtblTablaReportesMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtblTablaReportesMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jtblTablaReportes);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 630, 570));

        jLabel27.setBackground(new java.awt.Color(105, 105, 118));
        jLabel27.setFont(new java.awt.Font("Malgun Gothic", 0, 24)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(105, 105, 118));
        jLabel27.setText("Lista de reportes");
        jPanel2.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 710, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 840, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 790, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtblTablaReportesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtblTablaReportesMousePressed
        
    }//GEN-LAST:event_jtblTablaReportesMousePressed

    private void jtblTablaReportesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtblTablaReportesMouseClicked
        CRUDBoleta crud = new CRUDBoleta();
        int fila = jtblTablaReportes.getSelectedRow();
        if (fila != -1) {
            int idReporte = (int)jtblTablaReportes.getValueAt(fila, 0);
            crud.llenarListaBoletasParaReporte(idReporte);
            new ControladorConsultaBoleta(ControladorPanelPrincipal.getVentanaPrincipal(), new ConsultarBoleta(), true);
        }
    }//GEN-LAST:event_jtblTablaReportesMouseClicked

    private void jtblTablaReportesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtblTablaReportesMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jtblTablaReportesMouseEntered


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JButton jbtnBuscarReportes;
    public com.toedter.calendar.JDateChooser jdchFechaFinal;
    public com.toedter.calendar.JDateChooser jdchFechaInicial;
    public javax.swing.JTable jtblTablaReportes;
    // End of variables declaration//GEN-END:variables
}
