/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Controlador.*;
import DAO.CRUDBoleta;
import DAO.CRUDProductos;
import Formato.Messages;
import Modelo.Producto;
import java.awt.Desktop;
import java.awt.Font;
import java.awt.FontFormatException;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.io.InputStream;
import java.net.URI;

/**
 *
 * @author Programmer
 */
public class PanelHome extends javax.swing.JPanel {
    CRUDProductos crud = new CRUDProductos();
    boolean flag = true;

    /**
     * Creates new form Home
     */
    public PanelHome() {
        initComponents();
        jlblCheck.setVisible(false);
        jpnlWithOut.setVisible(false);
        jlblStockVerificado.setVisible(false);
        jlblRepuestosSinStock.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnlInterfaz = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        try(InputStream is = getClass().getResourceAsStream("/Recursos/Font Awesome 6 Free-Solid-900.otf")){
            Font fontAwesome = Font.createFont(Font.TRUETYPE_FONT, is);
            fontAwesome = fontAwesome.deriveFont(Font.PLAIN, 18f);
            jlblLupa = new javax.swing.JLabel();
            jlblLupa.setFont(fontAwesome);
        }catch (IOException | FontFormatException exp) {
            exp.printStackTrace();
        }
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        try(InputStream is = getClass().getResourceAsStream("/Recursos/Font Awesome 6 Free-Solid-900.otf")){
            Font fontAwesome = Font.createFont(Font.TRUETYPE_FONT, is);
            fontAwesome = fontAwesome.deriveFont(Font.PLAIN, 28f);
            jlblLastSell = new javax.swing.JLabel();
            jlblLastSell.setFont(fontAwesome);
        }catch (IOException | FontFormatException exp) {
            exp.printStackTrace();
        }
        jLabel9 = new javax.swing.JLabel();
        jlblUltimaBoleta = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        try(InputStream is = getClass().getResourceAsStream("/Recursos/Font Awesome 6 Free-Solid-900.otf")){
            Font fontAwesome = Font.createFont(Font.TRUETYPE_FONT, is);
            fontAwesome = fontAwesome.deriveFont(Font.PLAIN, 36f);
            jlblTiendaIcon = new javax.swing.JLabel();
            jlblTiendaIcon.setFont(fontAwesome);
        }catch (IOException | FontFormatException exp) {
            exp.printStackTrace();
        }
        jLabel10 = new javax.swing.JLabel();
        jlblIngresoDiario1 = new javax.swing.JLabel();
        try(InputStream is = getClass().getResourceAsStream("/Recursos/Font Awesome 6 Free-Solid-900.otf")){
            Font fontAwesome = Font.createFont(Font.TRUETYPE_FONT, is);
            fontAwesome = fontAwesome.deriveFont(Font.PLAIN, 28f);
            jlblPointerIcon = new javax.swing.JLabel();
            jlblPointerIcon.setFont(fontAwesome);
        }catch (IOException | FontFormatException exp) {
            exp.printStackTrace();
        }
        jPanel7 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        try(InputStream is = getClass().getResourceAsStream("/Recursos/Font Awesome 6 Free-Solid-900.otf")){
            Font fontAwesome = Font.createFont(Font.TRUETYPE_FONT, is);
            fontAwesome = fontAwesome.deriveFont(Font.PLAIN, 28f);
            jlblInventarioIcon = new javax.swing.JLabel();
            jlblInventarioIcon.setFont(fontAwesome);
        }catch (IOException | FontFormatException exp) {
            exp.printStackTrace();
        }
        jLabel8 = new javax.swing.JLabel();
        jlblInventario = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        try(InputStream is = getClass().getResourceAsStream("/Recursos/Font Awesome 6 Free-Solid-900.otf")){
            Font fontAwesome = Font.createFont(Font.TRUETYPE_FONT, is);
            fontAwesome = fontAwesome.deriveFont(Font.PLAIN, 28f);
            jlblDollarIcon = new javax.swing.JLabel();
            jlblDollarIcon.setFont(fontAwesome);
        }catch (IOException | FontFormatException exp) {
            exp.printStackTrace();
        }
        jlblIngresoDiario = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jlblStockVerificado = new javax.swing.JLabel();
        try(InputStream is = getClass().getResourceAsStream("/Recursos/Font Awesome 6 Free-Solid-900.otf")){
            Font fontAwesome = Font.createFont(Font.TRUETYPE_FONT, is);
            fontAwesome = fontAwesome.deriveFont(Font.PLAIN, 44f);
            jlblCheck = new javax.swing.JLabel();
            jlblCheck.setFont(fontAwesome);
        }catch (IOException | FontFormatException exp) {
            exp.printStackTrace();
        }
        jpnlWithOut = new javax.swing.JPanel();
        try(InputStream is = getClass().getResourceAsStream("/Recursos/Font Awesome 6 Free-Solid-900.otf")){
            Font fontAwesome = Font.createFont(Font.TRUETYPE_FONT, is);
            fontAwesome = fontAwesome.deriveFont(Font.PLAIN, 28f);
            jlblWithOutStock = new javax.swing.JLabel();
            jlblWithOutStock.setFont(fontAwesome);
        }catch (IOException | FontFormatException exp) {
            exp.printStackTrace();
        }
        jlblProducto4 = new javax.swing.JLabel();
        jlblProducto1 = new javax.swing.JLabel();
        jlblProducto2 = new javax.swing.JLabel();
        jlblProducto3 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jlblRepuestosSinStock = new javax.swing.JLabel();
        jtxtBuscarRepuesto = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jpnlInterfaz.setBackground(new java.awt.Color(255, 255, 255));
        jpnlInterfaz.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpnlInterfazMouseClicked(evt);
            }
        });
        jpnlInterfaz.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(250, 250, 250));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlblLupa.setForeground(new java.awt.Color(38, 38, 38));
        jlblLupa.setText("\uf002");
        jPanel1.add(jlblLupa, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 30, 30));

        jpnlInterfaz.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 70, 50));

        jPanel4.setBackground(new java.awt.Color(252, 252, 252));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(243, 243, 243)));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
        });
        jPanel4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPanel4KeyPressed(evt);
            }
        });
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Malgun Gothic", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(20, 23, 31));
        jLabel3.setText("Overview");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        jLabel6.setFont(new java.awt.Font("Malgun Gothic", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(105, 105, 118));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Buenos noches!");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 110, -1));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(247, 247, 247)));
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel5MouseClicked(evt);
            }
        });
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setBackground(new java.awt.Color(250, 250, 250));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlblLastSell.setForeground(new java.awt.Color(38, 38, 38));
        jlblLastSell.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblLastSell.setText("\uf06e");
        jPanel9.add(jlblLastSell, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 50));

        jPanel5.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 70, 70));

        jLabel9.setFont(new java.awt.Font("Malgun Gothic", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(105, 105, 118));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("Ultima venta");
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 80, -1));

        jlblUltimaBoleta.setFont(new java.awt.Font("Malgun Gothic", 1, 24)); // NOI18N
        jPanel5.add(jlblUltimaBoleta, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 130, 30));

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 300, 110));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(247, 247, 247)));
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel6MouseClicked(evt);
            }
        });
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel11.setBackground(new java.awt.Color(250, 250, 250));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlblTiendaIcon.setForeground(new java.awt.Color(38, 38, 38));
        jlblTiendaIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblTiendaIcon.setText("\uf54e");
        jPanel11.add(jlblTiendaIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, 90));

        jPanel6.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 110, 110));

        jLabel10.setFont(new java.awt.Font("Malgun Gothic", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(105, 105, 118));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("Link de pagina de compra");
        jPanel6.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 190, -1));

        jlblIngresoDiario1.setFont(new java.awt.Font("Malgun Gothic", 0, 36)); // NOI18N
        jlblIngresoDiario1.setText("CROSLAND REPUESTOS");
        jPanel6.add(jlblIngresoDiario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 400, 40));

        jlblPointerIcon.setForeground(new java.awt.Color(38, 38, 38));
        jlblPointerIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblPointerIcon.setText("\uf245");
        jPanel6.add(jlblPointerIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 80, 50, 50));

        jPanel4.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 500, 730, 170));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(247, 247, 247)));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(250, 250, 250));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlblInventarioIcon.setForeground(new java.awt.Color(38, 38, 38));
        jlblInventarioIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblInventarioIcon.setText("\uf200");
        jPanel3.add(jlblInventarioIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 50));

        jPanel7.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 70, 70));

        jLabel8.setFont(new java.awt.Font("Malgun Gothic", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(105, 105, 118));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("Inventario");
        jPanel7.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 80, -1));

        jlblInventario.setFont(new java.awt.Font("Malgun Gothic", 1, 24)); // NOI18N
        jPanel7.add(jlblInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 130, 30));

        jPanel4.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 300, 110));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(247, 247, 247)));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Malgun Gothic", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(105, 105, 118));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Ingresos");
        jPanel8.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 80, -1));

        jPanel2.setBackground(new java.awt.Color(250, 250, 250));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlblDollarIcon.setForeground(new java.awt.Color(38, 38, 38));
        jlblDollarIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblDollarIcon.setText("\uf155");
        jPanel2.add(jlblDollarIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 50));

        jPanel8.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 70, 70));

        jlblIngresoDiario.setFont(new java.awt.Font("Malgun Gothic", 1, 24)); // NOI18N
        jPanel8.add(jlblIngresoDiario, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 130, 30));

        jPanel4.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 300, 110));

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(247, 247, 247)));
        jPanel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel10MouseClicked(evt);
            }
        });
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlblStockVerificado.setFont(new java.awt.Font("Malgun Gothic", 0, 14)); // NOI18N
        jlblStockVerificado.setForeground(new java.awt.Color(105, 105, 118));
        jlblStockVerificado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblStockVerificado.setText("Stock verificado");
        jPanel10.add(jlblStockVerificado, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 160, -1));

        jlblCheck.setForeground(new java.awt.Color(38, 38, 38));
        jlblCheck.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblCheck.setText("\uf00c");
        jPanel10.add(jlblCheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 60, 60));

        jpnlWithOut.setBackground(new java.awt.Color(250, 250, 250));
        jpnlWithOut.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlblWithOutStock.setForeground(new java.awt.Color(38, 38, 38));
        jlblWithOutStock.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblWithOutStock.setText("\uf071");
        jpnlWithOut.add(jlblWithOutStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 50));

        jPanel10.add(jpnlWithOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 70, 70));

        jlblProducto4.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        jlblProducto4.setForeground(new java.awt.Color(20, 23, 31));
        jPanel10.add(jlblProducto4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 130, 30));

        jlblProducto1.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        jlblProducto1.setForeground(new java.awt.Color(20, 23, 31));
        jPanel10.add(jlblProducto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 130, 30));

        jlblProducto2.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        jlblProducto2.setForeground(new java.awt.Color(20, 23, 31));
        jPanel10.add(jlblProducto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 130, 30));

        jlblProducto3.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        jlblProducto3.setForeground(new java.awt.Color(20, 23, 31));
        jPanel10.add(jlblProducto3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 130, 30));

        jLabel13.setFont(new java.awt.Font("Malgun Gothic", 0, 14)); // NOI18N
        jLabel13.setText(". . .");
        jPanel10.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 330, 30, -1));

        jLabel12.setFont(new java.awt.Font("Malgun Gothic", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(105, 105, 118));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setText("Mantenimiento de inventario");
        jPanel10.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 190, -1));

        jlblRepuestosSinStock.setFont(new java.awt.Font("Malgun Gothic", 0, 14)); // NOI18N
        jlblRepuestosSinStock.setForeground(new java.awt.Color(105, 105, 118));
        jlblRepuestosSinStock.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblRepuestosSinStock.setText("Repuestos sin stock");
        jPanel10.add(jlblRepuestosSinStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 130, -1));

        jPanel4.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, 360, 370));

        jpnlInterfaz.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 840, 700));

        jtxtBuscarRepuesto.setBackground(new java.awt.Color(250, 250, 250));
        jtxtBuscarRepuesto.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jtxtBuscarRepuesto.setForeground(new java.awt.Color(38, 38, 38));
        jtxtBuscarRepuesto.setText("Buscar repuesto");
        jtxtBuscarRepuesto.setBorder(null);
        jtxtBuscarRepuesto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtBuscarRepuestoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtBuscarRepuestoKeyTyped(evt);
            }
        });
        jpnlInterfaz.add(jtxtBuscarRepuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 430, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon_user.png"))); // NOI18N
        jpnlInterfaz.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Malgun Gothic", 0, 16)); // NOI18N
        jLabel2.setText("Administrador");
        jpnlInterfaz.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 20, -1, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnlInterfaz, javax.swing.GroupLayout.PREFERRED_SIZE, 840, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnlInterfaz, javax.swing.GroupLayout.PREFERRED_SIZE, 790, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jpnlInterfazMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnlInterfazMouseClicked

    }//GEN-LAST:event_jpnlInterfazMouseClicked

    private void jtxtBuscarRepuestoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtBuscarRepuestoKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            VentanaPrincipal vista = ControladorPanelPrincipal.getVentanaPrincipal();
            if (!jtxtBuscarRepuesto.getText().equals("")) {
                Producto prod = crud.obtenerProducto(crud.obtenerIdProducto(jtxtBuscarRepuesto.getText()));
                if (prod.getNombre() != null) {
                    new ControladorProducto(vista, new PanelProducto(), true, jtxtBuscarRepuesto.getText());
                    ControladorPanelPrincipal.setFocusButton(vista.jbtnRepuestos, vista.jlblRepuestosIcon);
                    vista.turnAllFalse();
                    vista.botonRepuestos = true;
                } else {
                    Messages.show("El producto no esta registrado");
                    jtxtBuscarRepuesto.setText("");
                }
            } else {
                Messages.show("Digite un codigo");
            }
        }
    }//GEN-LAST:event_jtxtBuscarRepuestoKeyReleased

    private void jPanel4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanel4KeyPressed
        //
    }//GEN-LAST:event_jPanel4KeyPressed

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
        if (jtxtBuscarRepuesto.getText().equals("")) {
            jtxtBuscarRepuesto.setText("Buscar repuesto");
            jPanel4.requestFocus();
            flag = true;
        }
    }//GEN-LAST:event_jPanel4MouseClicked

    private void jtxtBuscarRepuestoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtBuscarRepuestoKeyTyped
        if (flag) {
            jtxtBuscarRepuesto.setText("");
            flag = false;
        }
    }//GEN-LAST:event_jtxtBuscarRepuestoKeyTyped

    private void jPanel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseClicked
        CRUDBoleta crudBoleta = new CRUDBoleta();
        int idBoleta = crudBoleta.obtenerActualIdBoleta();
        if (idBoleta != 0) {
            new ControladorBoleta(new VentanaBoleta(), idBoleta);
        }
    }//GEN-LAST:event_jPanel5MouseClicked

    private void jPanel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel10MouseClicked
        if (jlblRepuestosSinStock.isVisible()) {
            new ControladorProductosSinStock(new VentanaProductosSinStock());
        }
    }//GEN-LAST:event_jPanel10MouseClicked

    private void jPanel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseClicked
        try {
            if (Desktop.isDesktopSupported()) {
                Desktop desktop = Desktop.getDesktop();
                if (desktop.isSupported(Desktop.Action.BROWSE)) {
                    desktop.browse(new URI("https://www.croslandrepuestos.com.pe/"));
                }
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_jPanel6MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    public javax.swing.JLabel jlblCheck;
    private javax.swing.JLabel jlblDollarIcon;
    public javax.swing.JLabel jlblIngresoDiario;
    public javax.swing.JLabel jlblIngresoDiario1;
    public javax.swing.JLabel jlblInventario;
    private javax.swing.JLabel jlblInventarioIcon;
    private javax.swing.JLabel jlblLastSell;
    private javax.swing.JLabel jlblLupa;
    private javax.swing.JLabel jlblPointerIcon;
    public javax.swing.JLabel jlblProducto1;
    public javax.swing.JLabel jlblProducto2;
    public javax.swing.JLabel jlblProducto3;
    public javax.swing.JLabel jlblProducto4;
    public javax.swing.JLabel jlblRepuestosSinStock;
    public javax.swing.JLabel jlblStockVerificado;
    private javax.swing.JLabel jlblTiendaIcon;
    public javax.swing.JLabel jlblUltimaBoleta;
    public javax.swing.JLabel jlblWithOutStock;
    private javax.swing.JPanel jpnlInterfaz;
    public javax.swing.JPanel jpnlWithOut;
    public javax.swing.JTextField jtxtBuscarRepuesto;
    // End of variables declaration//GEN-END:variables
}
