/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

/**
 *
 * @author Programmer
 */
public class PanelClientes extends javax.swing.JPanel {

    /**
     * Creates new form Producto
     */
    public PanelClientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnlInterfaz = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtxtDniCliente = new javax.swing.JTextField();
        jbtnBuscarCliente = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jtxtNombreCliente = new javax.swing.JTextField();
        jbtnEditar = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel25 = new javax.swing.JLabel();
        jtxtDireccionCliente = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jSeparator19 = new javax.swing.JSeparator();
        jtxtTelefonoCliente = new javax.swing.JTextField();
        jSeparator20 = new javax.swing.JSeparator();
        jLabel27 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jtxtDniClienteAgregar = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        jbtnAgregar = new javax.swing.JButton();
        jlblExito = new javax.swing.JLabel();
        jtxtNombreClienteAgregar = new javax.swing.JTextField();
        jSeparator13 = new javax.swing.JSeparator();
        jLabel23 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jtxtDireccionClienteAdd = new javax.swing.JTextField();
        jSeparator17 = new javax.swing.JSeparator();
        jLabel24 = new javax.swing.JLabel();
        jtxtTelefonoClienteAdd = new javax.swing.JTextField();
        jSeparator18 = new javax.swing.JSeparator();

        jpnlInterfaz.setBackground(new java.awt.Color(255, 255, 255));
        jpnlInterfaz.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpnlInterfazMouseClicked(evt);
            }
        });
        jpnlInterfaz.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(252, 252, 252));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(243, 243, 243)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(105, 105, 118));
        jLabel1.setText("DNI :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, 30));

        jtxtDniCliente.setBackground(new java.awt.Color(250, 250, 250));
        jtxtDniCliente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtxtDniCliente.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jtxtDniCliente.setBorder(null);
        jtxtDniCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtDniClienteActionPerformed(evt);
            }
        });
        jPanel1.add(jtxtDniCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 210, 30));

        jbtnBuscarCliente.setBackground(new java.awt.Color(255, 255, 254));
        jbtnBuscarCliente.setFont(new java.awt.Font("Malgun Gothic", 1, 12)); // NOI18N
        jbtnBuscarCliente.setForeground(new java.awt.Color(105, 105, 118));
        jbtnBuscarCliente.setText("BUSCAR");
        jPanel1.add(jbtnBuscarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, 100, 30));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 210, 30));

        jLabel2.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(105, 105, 118));
        jLabel2.setText("Nombres y Apellidos");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 160, 30));

        jtxtNombreCliente.setBackground(new java.awt.Color(250, 250, 250));
        jtxtNombreCliente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtxtNombreCliente.setBorder(null);
        jtxtNombreCliente.setFocusable(false);
        jtxtNombreCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtNombreClienteActionPerformed(evt);
            }
        });
        jPanel1.add(jtxtNombreCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 310, 30));

        jbtnEditar.setBackground(new java.awt.Color(20, 23, 31));
        jbtnEditar.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        jbtnEditar.setForeground(new java.awt.Color(255, 255, 255));
        jbtnEditar.setText("EDITAR");
        jbtnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEditarActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 590, 160, 40));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 310, 10));

        jLabel25.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(105, 105, 118));
        jLabel25.setText("Direccion");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 100, 30));

        jtxtDireccionCliente.setBackground(new java.awt.Color(250, 250, 250));
        jtxtDireccionCliente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtxtDireccionCliente.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jtxtDireccionCliente.setBorder(null);
        jtxtDireccionCliente.setFocusable(false);
        jtxtDireccionCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtDireccionClienteActionPerformed(evt);
            }
        });
        jPanel1.add(jtxtDireccionCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 310, 30));

        jLabel26.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(105, 105, 118));
        jLabel26.setText("Telefono");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 430, 80, 30));

        jSeparator19.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator19, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, 310, 10));

        jtxtTelefonoCliente.setBackground(new java.awt.Color(250, 250, 250));
        jtxtTelefonoCliente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtxtTelefonoCliente.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jtxtTelefonoCliente.setBorder(null);
        jtxtTelefonoCliente.setFocusable(false);
        jtxtTelefonoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtTelefonoClienteActionPerformed(evt);
            }
        });
        jPanel1.add(jtxtTelefonoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 460, 310, 30));

        jSeparator20.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator20, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 490, 310, 10));

        jLabel27.setBackground(new java.awt.Color(105, 105, 118));
        jLabel27.setFont(new java.awt.Font("Malgun Gothic", 0, 24)); // NOI18N
        jLabel27.setText("Busqueda de Cliente");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, -1, -1));

        jpnlInterfaz.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 420, 790));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(105, 105, 118));
        jLabel13.setText("DNI");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, 30));

        jtxtDniClienteAgregar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtxtDniClienteAgregar.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jtxtDniClienteAgregar.setBorder(null);
        jtxtDniClienteAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtDniClienteAgregarActionPerformed(evt);
            }
        });
        jPanel3.add(jtxtDniClienteAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 250, 30));

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 250, 20));

        jLabel14.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(105, 105, 118));
        jLabel14.setText("Nombres y Apellidos");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, 30));

        jbtnAgregar.setBackground(new java.awt.Color(20, 23, 31));
        jbtnAgregar.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        jbtnAgregar.setForeground(new java.awt.Color(241, 240, 243));
        jbtnAgregar.setText("AGREGAR");
        jPanel3.add(jbtnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 590, 120, 40));

        jlblExito.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jlblExito.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel3.add(jlblExito, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 650, 310, 40));

        jtxtNombreClienteAgregar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtxtNombreClienteAgregar.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jtxtNombreClienteAgregar.setBorder(null);
        jtxtNombreClienteAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtNombreClienteAgregarActionPerformed(evt);
            }
        });
        jPanel3.add(jtxtNombreClienteAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 300, 30));

        jSeparator13.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 300, 10));

        jLabel23.setBackground(new java.awt.Color(105, 105, 118));
        jLabel23.setFont(new java.awt.Font("Malgun Gothic", 0, 24)); // NOI18N
        jLabel23.setText("Registrar cliente");
        jPanel3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, -1, -1));

        jLabel18.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(105, 105, 118));
        jLabel18.setText("Direccion");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, -1, 30));

        jtxtDireccionClienteAdd.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtxtDireccionClienteAdd.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jtxtDireccionClienteAdd.setBorder(null);
        jtxtDireccionClienteAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtDireccionClienteAddActionPerformed(evt);
            }
        });
        jPanel3.add(jtxtDireccionClienteAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 300, 30));

        jSeparator17.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jSeparator17, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, 300, 10));

        jLabel24.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(105, 105, 118));
        jLabel24.setText("Telefono");
        jPanel3.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 430, -1, 30));

        jtxtTelefonoClienteAdd.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtxtTelefonoClienteAdd.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jtxtTelefonoClienteAdd.setBorder(null);
        jtxtTelefonoClienteAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtTelefonoClienteAddActionPerformed(evt);
            }
        });
        jPanel3.add(jtxtTelefonoClienteAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 460, 300, 30));

        jSeparator18.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jSeparator18, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 490, 300, 10));

        jpnlInterfaz.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 790));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnlInterfaz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnlInterfaz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jpnlInterfazMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnlInterfazMouseClicked

    }//GEN-LAST:event_jpnlInterfazMouseClicked

    private void jtxtDniClienteAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtDniClienteAgregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtDniClienteAgregarActionPerformed

    private void jtxtNombreClienteAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtNombreClienteAgregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtNombreClienteAgregarActionPerformed

    private void jtxtDireccionClienteAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtDireccionClienteAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtDireccionClienteAddActionPerformed

    private void jtxtTelefonoClienteAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtTelefonoClienteAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtTelefonoClienteAddActionPerformed

    private void jbtnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnEditarActionPerformed

    private void jtxtNombreClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtNombreClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtNombreClienteActionPerformed

    private void jtxtDniClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtDniClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtDniClienteActionPerformed

    private void jtxtDireccionClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtDireccionClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtDireccionClienteActionPerformed

    private void jtxtTelefonoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtTelefonoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtTelefonoClienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator20;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    public javax.swing.JButton jbtnAgregar;
    public javax.swing.JButton jbtnBuscarCliente;
    public javax.swing.JButton jbtnEditar;
    public javax.swing.JLabel jlblExito;
    private javax.swing.JPanel jpnlInterfaz;
    public javax.swing.JTextField jtxtDireccionCliente;
    public javax.swing.JTextField jtxtDireccionClienteAdd;
    public javax.swing.JTextField jtxtDniCliente;
    public javax.swing.JTextField jtxtDniClienteAgregar;
    public javax.swing.JTextField jtxtNombreCliente;
    public javax.swing.JTextField jtxtNombreClienteAgregar;
    public javax.swing.JTextField jtxtTelefonoCliente;
    public javax.swing.JTextField jtxtTelefonoClienteAdd;
    // End of variables declaration//GEN-END:variables
}
