/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Formato.Messages;

/**
 *
 * @author Programmer
 */
public class PanelProducto extends javax.swing.JPanel {

    /**
     * Creates new form Producto
     */
    public PanelProducto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnlInterfaz = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtxtCodigoBusqueda = new javax.swing.JTextField();
        jbtnBuscarProducto = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jtxtNombreBusqueda = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtxtStockBusqueda = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jtxtCostoBusqueda = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jtxtPrecioVentaBusqueda = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jbtnDelete = new javax.swing.JButton();
        jbtnEditar = new javax.swing.JButton();
        jcbxMarcaBusqueda = new javax.swing.JComboBox<>();
        jcbxProveedorBusqueda = new javax.swing.JComboBox<>();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel22 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jbtnAumentar = new javax.swing.JButton();
        jtxtCodigoAumento = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jSeparator14 = new javax.swing.JSeparator();
        jLabel21 = new javax.swing.JLabel();
        jtxtStockAumento = new javax.swing.JTextField();
        jSeparator15 = new javax.swing.JSeparator();
        jlblExitoAumento = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jtxtCodigoRegistro = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        Costo = new javax.swing.JLabel();
        jtxtStockRegistro = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        jLabel19 = new javax.swing.JLabel();
        jSeparator11 = new javax.swing.JSeparator();
        jbtnAgregar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jtxtCostoSinIgvRegistro = new javax.swing.JTextField();
        jtxtPrecioVentaRegistro = new javax.swing.JTextField();
        jcbxProveedorRegistro = new javax.swing.JComboBox<>();
        jlblExito = new javax.swing.JLabel();
        jtxtNombreRegistro = new javax.swing.JTextField();
        jSeparator13 = new javax.swing.JSeparator();
        jcbxMarcaRegistro = new javax.swing.JComboBox<>();
        jtxtCostoRegistro = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jSeparator16 = new javax.swing.JSeparator();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpnlInterfaz.setBackground(new java.awt.Color(255, 255, 255));
        jpnlInterfaz.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpnlInterfazMouseClicked(evt);
            }
        });
        jpnlInterfaz.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(jpnlInterfaz, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Malgun Gothic", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(105, 105, 118));
        jLabel1.setText("Codigo :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, 30));

        jtxtCodigoBusqueda.setFont(new java.awt.Font("Malgun Gothic", 0, 14)); // NOI18N
        jtxtCodigoBusqueda.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jtxtCodigoBusqueda.setBorder(null);
        jtxtCodigoBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtCodigoBusquedaActionPerformed(evt);
            }
        });
        jPanel1.add(jtxtCodigoBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 160, 30));

        jbtnBuscarProducto.setBackground(new java.awt.Color(255, 255, 254));
        jbtnBuscarProducto.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        jbtnBuscarProducto.setText("BUSCAR");
        jPanel1.add(jbtnBuscarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 100, 30));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 160, 30));

        jLabel2.setFont(new java.awt.Font("Malgun Gothic", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(105, 105, 118));
        jLabel2.setText("Nombre del repuesto");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, 30));

        jtxtNombreBusqueda.setFont(new java.awt.Font("Malgun Gothic", 0, 14)); // NOI18N
        jtxtNombreBusqueda.setBorder(null);
        jtxtNombreBusqueda.setFocusable(false);
        jtxtNombreBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtNombreBusquedaActionPerformed(evt);
            }
        });
        jPanel1.add(jtxtNombreBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 330, 30));

        jLabel3.setFont(new java.awt.Font("Malgun Gothic", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(105, 105, 118));
        jLabel3.setText("Marca");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, 30));

        jLabel4.setFont(new java.awt.Font("Malgun Gothic", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(105, 105, 118));
        jLabel4.setText("Proveedor");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, 30));

        jLabel5.setFont(new java.awt.Font("Malgun Gothic", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(105, 105, 118));
        jLabel5.setText("Stock");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(329, 360, -1, 30));

        jtxtStockBusqueda.setFont(new java.awt.Font("Malgun Gothic", 0, 14)); // NOI18N
        jtxtStockBusqueda.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtStockBusqueda.setBorder(null);
        jtxtStockBusqueda.setFocusable(false);
        jtxtStockBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtStockBusquedaActionPerformed(evt);
            }
        });
        jPanel1.add(jtxtStockBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 390, 70, 30));

        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 420, 70, 10));

        jLabel6.setFont(new java.awt.Font("Malgun Gothic", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(105, 105, 118));
        jLabel6.setText("Costo");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, -1, 30));

        jtxtCostoBusqueda.setFont(new java.awt.Font("Malgun Gothic", 0, 14)); // NOI18N
        jtxtCostoBusqueda.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtCostoBusqueda.setBorder(null);
        jtxtCostoBusqueda.setFocusable(false);
        jtxtCostoBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtCostoBusquedaActionPerformed(evt);
            }
        });
        jPanel1.add(jtxtCostoBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 80, 30));

        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 80, 10));

        jLabel7.setFont(new java.awt.Font("Malgun Gothic", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(105, 105, 118));
        jLabel7.setText("Precio de venta");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, 120, 30));

        jtxtPrecioVentaBusqueda.setFont(new java.awt.Font("Malgun Gothic", 0, 14)); // NOI18N
        jtxtPrecioVentaBusqueda.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtPrecioVentaBusqueda.setBorder(null);
        jtxtPrecioVentaBusqueda.setFocusable(false);
        jtxtPrecioVentaBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtPrecioVentaBusquedaActionPerformed(evt);
            }
        });
        jPanel1.add(jtxtPrecioVentaBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, 120, 30));

        jSeparator7.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 420, 120, 10));

        jbtnDelete.setBackground(new java.awt.Color(20, 23, 31));
        jbtnDelete.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        jbtnDelete.setForeground(new java.awt.Color(241, 240, 243));
        jbtnDelete.setText("DELETE");
        jPanel1.add(jbtnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 460, 110, 40));

        jbtnEditar.setBackground(new java.awt.Color(20, 23, 31));
        jbtnEditar.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        jbtnEditar.setForeground(new java.awt.Color(255, 255, 255));
        jbtnEditar.setText("EDITAR");
        jbtnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEditarActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, 160, 40));

        jcbxMarcaBusqueda.setBackground(new java.awt.Color(255, 255, 254));
        jcbxMarcaBusqueda.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        jcbxMarcaBusqueda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BAJAJ", "TVS" }));
        jcbxMarcaBusqueda.setEnabled(false);
        jcbxMarcaBusqueda.setFocusable(false);
        jPanel1.add(jcbxMarcaBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 210, 30));

        jcbxProveedorBusqueda.setBackground(new java.awt.Color(255, 255, 254));
        jcbxProveedorBusqueda.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        jcbxProveedorBusqueda.setEnabled(false);
        jcbxProveedorBusqueda.setFocusable(false);
        jPanel1.add(jcbxProveedorBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 210, 30));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 330, 10));

        jLabel22.setFont(new java.awt.Font("Malgun Gothic", 0, 24)); // NOI18N
        jLabel22.setText("Aumento de stock");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 523, -1, 40));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnAumentar.setBackground(new java.awt.Color(20, 23, 31));
        jbtnAumentar.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        jbtnAumentar.setForeground(new java.awt.Color(241, 240, 243));
        jbtnAumentar.setText("AUMENTAR");
        jPanel4.add(jbtnAumentar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 160, 40));

        jtxtCodigoAumento.setFont(new java.awt.Font("Malgun Gothic", 0, 14)); // NOI18N
        jtxtCodigoAumento.setBorder(null);
        jtxtCodigoAumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtCodigoAumentoActionPerformed(evt);
            }
        });
        jPanel4.add(jtxtCodigoAumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 200, 30));

        jLabel20.setFont(new java.awt.Font("Malgun Gothic", 0, 16)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(105, 105, 118));
        jLabel20.setText("Codigo");
        jPanel4.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, 30));

        jSeparator14.setForeground(new java.awt.Color(0, 0, 0));
        jPanel4.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 200, 20));

        jLabel21.setFont(new java.awt.Font("Malgun Gothic", 0, 16)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(105, 105, 118));
        jLabel21.setText("Stock");
        jPanel4.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, 50, 30));

        jtxtStockAumento.setFont(new java.awt.Font("Malgun Gothic", 0, 14)); // NOI18N
        jtxtStockAumento.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtStockAumento.setBorder(null);
        jtxtStockAumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtStockAumentoActionPerformed(evt);
            }
        });
        jPanel4.add(jtxtStockAumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 80, 30));

        jSeparator15.setForeground(new java.awt.Color(0, 0, 0));
        jPanel4.add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 80, 20));

        jlblExitoAumento.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        jlblExitoAumento.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel4.add(jlblExitoAumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 320, 40));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, 400, 240));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, -1));

        jPanel3.setBackground(new java.awt.Color(252, 252, 252));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(243, 243, 243)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Malgun Gothic", 0, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(105, 105, 118));
        jLabel13.setText("Codigo");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, 30));

        jtxtCodigoRegistro.setBackground(new java.awt.Color(252, 252, 252));
        jtxtCodigoRegistro.setFont(new java.awt.Font("Malgun Gothic", 0, 14)); // NOI18N
        jtxtCodigoRegistro.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jtxtCodigoRegistro.setBorder(null);
        jtxtCodigoRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtCodigoRegistroActionPerformed(evt);
            }
        });
        jPanel3.add(jtxtCodigoRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 250, 30));

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 250, 20));

        jLabel14.setFont(new java.awt.Font("Malgun Gothic", 0, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(105, 105, 118));
        jLabel14.setText("Nombre del repuesto");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, 30));

        jLabel15.setFont(new java.awt.Font("Malgun Gothic", 0, 16)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(105, 105, 118));
        jLabel15.setText("Marca");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, -1, 30));

        jLabel16.setFont(new java.awt.Font("Malgun Gothic", 0, 16)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(105, 105, 118));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel16.setText("Proveedor");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 80, 30));

        jLabel17.setFont(new java.awt.Font("Malgun Gothic", 0, 16)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(105, 105, 118));
        jLabel17.setText("Stock");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 440, 50, 30));

        jSeparator9.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 500, 130, 10));

        Costo.setFont(new java.awt.Font("Malgun Gothic", 0, 16)); // NOI18N
        Costo.setForeground(new java.awt.Color(105, 105, 118));
        Costo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Costo.setText("Costo");
        jPanel3.add(Costo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 530, 50, 30));

        jtxtStockRegistro.setBackground(new java.awt.Color(252, 252, 252));
        jtxtStockRegistro.setFont(new java.awt.Font("Malgun Gothic", 0, 14)); // NOI18N
        jtxtStockRegistro.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jtxtStockRegistro.setBorder(null);
        jtxtStockRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtStockRegistroActionPerformed(evt);
            }
        });
        jPanel3.add(jtxtStockRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 470, 130, 30));

        jSeparator10.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 590, 130, 10));

        jLabel19.setFont(new java.awt.Font("Malgun Gothic", 0, 16)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(105, 105, 118));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel19.setText("Precio venta");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 530, 100, 30));

        jSeparator11.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 500, 140, 10));

        jbtnAgregar.setBackground(new java.awt.Color(20, 23, 31));
        jbtnAgregar.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        jbtnAgregar.setForeground(new java.awt.Color(241, 240, 243));
        jbtnAgregar.setText("AGREGAR");
        jPanel3.add(jbtnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 700, 120, 40));

        jLabel8.setFont(new java.awt.Font("Malgun Gothic", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(105, 105, 118));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Costo sin IGV");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 440, 140, 30));

        jtxtCostoSinIgvRegistro.setBackground(new java.awt.Color(252, 252, 252));
        jtxtCostoSinIgvRegistro.setFont(new java.awt.Font("Malgun Gothic", 0, 14)); // NOI18N
        jtxtCostoSinIgvRegistro.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtCostoSinIgvRegistro.setBorder(null);
        jtxtCostoSinIgvRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtCostoSinIgvRegistroActionPerformed(evt);
            }
        });
        jPanel3.add(jtxtCostoSinIgvRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 470, 140, 30));

        jtxtPrecioVentaRegistro.setBackground(new java.awt.Color(252, 252, 252));
        jtxtPrecioVentaRegistro.setFont(new java.awt.Font("Malgun Gothic", 0, 14)); // NOI18N
        jtxtPrecioVentaRegistro.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtPrecioVentaRegistro.setBorder(null);
        jtxtPrecioVentaRegistro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtPrecioVentaRegistroFocusGained(evt);
            }
        });
        jtxtPrecioVentaRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtPrecioVentaRegistroActionPerformed(evt);
            }
        });
        jPanel3.add(jtxtPrecioVentaRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 560, 140, 30));

        jcbxProveedorRegistro.setBackground(new java.awt.Color(255, 255, 254));
        jcbxProveedorRegistro.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        jPanel3.add(jcbxProveedorRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, 210, 30));

        jlblExito.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        jlblExito.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel3.add(jlblExito, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 640, 310, 40));

        jtxtNombreRegistro.setBackground(new java.awt.Color(252, 252, 252));
        jtxtNombreRegistro.setFont(new java.awt.Font("Malgun Gothic", 0, 14)); // NOI18N
        jtxtNombreRegistro.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jtxtNombreRegistro.setBorder(null);
        jtxtNombreRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtNombreRegistroActionPerformed(evt);
            }
        });
        jPanel3.add(jtxtNombreRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 310, 30));

        jSeparator13.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 310, 10));

        jcbxMarcaRegistro.setBackground(new java.awt.Color(255, 255, 254));
        jcbxMarcaRegistro.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        jcbxMarcaRegistro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BAJAJ", "TVS" }));
        jPanel3.add(jcbxMarcaRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 210, 30));

        jtxtCostoRegistro.setBackground(new java.awt.Color(252, 252, 252));
        jtxtCostoRegistro.setFont(new java.awt.Font("Malgun Gothic", 0, 14)); // NOI18N
        jtxtCostoRegistro.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jtxtCostoRegistro.setBorder(null);
        jtxtCostoRegistro.setFocusable(false);
        jtxtCostoRegistro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtCostoRegistroFocusGained(evt);
            }
        });
        jtxtCostoRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtCostoRegistroActionPerformed(evt);
            }
        });
        jPanel3.add(jtxtCostoRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 560, 130, 30));

        jLabel23.setBackground(new java.awt.Color(105, 105, 118));
        jLabel23.setFont(new java.awt.Font("Malgun Gothic", 0, 24)); // NOI18N
        jLabel23.setText("Registrar repuesto");
        jPanel3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, -1, -1));

        jSeparator16.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 590, 140, 10));

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 420, 790));
    }// </editor-fold>//GEN-END:initComponents

    private void jpnlInterfazMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnlInterfazMouseClicked

    }//GEN-LAST:event_jpnlInterfazMouseClicked

    private void jtxtCodigoBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtCodigoBusquedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtCodigoBusquedaActionPerformed

    private void jtxtNombreBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtNombreBusquedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtNombreBusquedaActionPerformed

    private void jtxtStockBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtStockBusquedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtStockBusquedaActionPerformed

    private void jtxtCostoBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtCostoBusquedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtCostoBusquedaActionPerformed

    private void jtxtPrecioVentaBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtPrecioVentaBusquedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtPrecioVentaBusquedaActionPerformed

    private void jtxtCodigoAumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtCodigoAumentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtCodigoAumentoActionPerformed

    private void jtxtStockAumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtStockAumentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtStockAumentoActionPerformed

    private void jtxtCodigoRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtCodigoRegistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtCodigoRegistroActionPerformed

    private void jtxtStockRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtStockRegistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtStockRegistroActionPerformed

    private void jtxtCostoSinIgvRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtCostoSinIgvRegistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtCostoSinIgvRegistroActionPerformed

    private void jtxtPrecioVentaRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtPrecioVentaRegistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtPrecioVentaRegistroActionPerformed

    private void jtxtNombreRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtNombreRegistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtNombreRegistroActionPerformed

    private void jtxtCostoRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtCostoRegistroActionPerformed
        
    }//GEN-LAST:event_jtxtCostoRegistroActionPerformed

    private void jbtnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnEditarActionPerformed

    private void jtxtCostoRegistroFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtCostoRegistroFocusGained
        
    }//GEN-LAST:event_jtxtCostoRegistroFocusGained

    private void jtxtPrecioVentaRegistroFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtPrecioVentaRegistroFocusGained
        if (!jtxtCostoSinIgvRegistro.getText().equals("")) {
            double costo = Double.parseDouble(jtxtCostoSinIgvRegistro.getText());
            jtxtCostoRegistro.setText(String.valueOf(costo + (costo * 0.18)));
        }
    }//GEN-LAST:event_jtxtPrecioVentaRegistroFocusGained


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Costo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator9;
    public javax.swing.JButton jbtnAgregar;
    public javax.swing.JButton jbtnAumentar;
    public javax.swing.JButton jbtnBuscarProducto;
    public javax.swing.JButton jbtnDelete;
    public javax.swing.JButton jbtnEditar;
    public javax.swing.JComboBox<String> jcbxMarcaBusqueda;
    public javax.swing.JComboBox<String> jcbxMarcaRegistro;
    public javax.swing.JComboBox<String> jcbxProveedorBusqueda;
    public javax.swing.JComboBox<String> jcbxProveedorRegistro;
    public javax.swing.JLabel jlblExito;
    public javax.swing.JLabel jlblExitoAumento;
    private javax.swing.JPanel jpnlInterfaz;
    public javax.swing.JTextField jtxtCodigoAumento;
    public javax.swing.JTextField jtxtCodigoBusqueda;
    public javax.swing.JTextField jtxtCodigoRegistro;
    public javax.swing.JTextField jtxtCostoBusqueda;
    public javax.swing.JTextField jtxtCostoRegistro;
    public javax.swing.JTextField jtxtCostoSinIgvRegistro;
    public javax.swing.JTextField jtxtNombreBusqueda;
    public javax.swing.JTextField jtxtNombreRegistro;
    public javax.swing.JTextField jtxtPrecioVentaBusqueda;
    public javax.swing.JTextField jtxtPrecioVentaRegistro;
    public javax.swing.JTextField jtxtStockAumento;
    public javax.swing.JTextField jtxtStockBusqueda;
    public javax.swing.JTextField jtxtStockRegistro;
    // End of variables declaration//GEN-END:variables
}
