/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Controlador.ControladorBoleta;

/**
 *
 * @author Programmer
 */
public class PanelReporteDia extends javax.swing.JPanel {

    /**
     * Creates new form ReporteDia
     */
    public PanelReporteDia() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jlblEmpty = new javax.swing.JLabel();
        jlblMontoTotal = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblTablaBoletas = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlblEmpty.setBackground(new java.awt.Color(0, 0, 0));
        jlblEmpty.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        jlblEmpty.setForeground(new java.awt.Color(105, 105, 118));
        jlblEmpty.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jlblEmpty, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 410, 370, 30));

        jlblMontoTotal.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jlblMontoTotal.setForeground(new java.awt.Color(20, 23, 31));
        jlblMontoTotal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel2.add(jlblMontoTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 40, 90, 60));

        jtblTablaBoletas.setFont(new java.awt.Font("Malgun Gothic", 0, 14)); // NOI18N
        jtblTablaBoletas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtblTablaBoletas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtblTablaBoletasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtblTablaBoletas);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 630, 570));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(20, 23, 31));
        jLabel2.setText("El total de ingresos generado en el dia fue S/");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 50, 540, 40));

        jLabel27.setBackground(new java.awt.Color(105, 105, 118));
        jLabel27.setFont(new java.awt.Font("Malgun Gothic", 0, 24)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(105, 105, 118));
        jLabel27.setText("Lista de boletas");
        jPanel2.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 710, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 840, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 790, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtblTablaBoletasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtblTablaBoletasMouseClicked
        int fila = jtblTablaBoletas.getSelectedRow();
        if (fila != -1) {
            String idBoleta = String.valueOf(jtblTablaBoletas.getValueAt(fila, 0));
            new ControladorBoleta(new VentanaBoleta(), Integer.parseInt(idBoleta));
        }
    }//GEN-LAST:event_jtblTablaBoletasMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel jlblEmpty;
    public javax.swing.JLabel jlblMontoTotal;
    public javax.swing.JTable jtblTablaBoletas;
    // End of variables declaration//GEN-END:variables
}
