/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.ControladorPanelPrincipal;
import utils.Messages;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;

/**
 *
 * @author ChikiCrema
 */
public class VentanaPass extends javax.swing.JFrame {

    char[] password = {'s', 'o', 'u', 't'};
    boolean flag = true;
    /**
     * Creates new form VentanaPas
     */
    public VentanaPass() {
        initComponents();
        this.setLocationRelativeTo(this);
        this.setTitle("Password");
        this.setVisible(true);
    }
    
    @Override
    public Image getIconImage() {
       Image icono = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/servimotos_icon.png"));
       return icono;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jpssPassword = new javax.swing.JPasswordField();
        jLabel17 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconImage(getIconImage());
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpssPassword.setFont(new java.awt.Font("Malgun Gothic", 0, 24)); // NOI18N
        jpssPassword.setForeground(new java.awt.Color(105, 105, 118));
        jpssPassword.setText("jPasswordField1eee");
        jpssPassword.setBorder(null);
        jpssPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jpssPasswordKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jpssPasswordKeyTyped(evt);
            }
        });
        jPanel1.add(jpssPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 354, 33));

        jLabel17.setBackground(new java.awt.Color(14, 14, 23));
        jLabel17.setFont(new java.awt.Font("Century Gothic", 0, 26)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(14, 14, 23));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("servimotos");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 140, 40));

        jLabel2.setFont(new java.awt.Font("Malgun Gothic", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(105, 105, 118));
        jLabel2.setText("Digite la contraseña");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, 30));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 360, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 265));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jpssPasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jpssPasswordKeyReleased
        int cont = 0;
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            char[] pass = jpssPassword.getPassword();
            if (password.length == pass.length) {
                for (int i = 0; i < pass.length; i++) {
                    if (password[i] == pass[i]) {
                        cont++;
                    }
                }
                if (cont == password.length) {
                    ControladorPanelPrincipal.isCorrectPassword = true;
                    dispose();
                    if (ControladorPanelPrincipal.panelReporte == 0) {
                        ControladorPanelPrincipal.openPanelReporteDia();
                    } else {
                        ControladorPanelPrincipal.openPanelConsultarReporte();
                    }
                } else {
                    dispose();
                    Messages.show("Contraseña incorrecta");
                }
            } else {
                dispose();
                Messages.show("Contraseña incorrecta");
            }
        }
    }//GEN-LAST:event_jpssPasswordKeyReleased

    private void jpssPasswordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jpssPasswordKeyTyped
        if (flag) {
            jpssPassword.setForeground(new Color(0, 0, 0));
            jpssPassword.setText("");
            flag = false;
        }
    }//GEN-LAST:event_jpssPasswordKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPasswordField jpssPassword;
    // End of variables declaration//GEN-END:variables
}
